config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :employees, controllers: {
    sessions: 'employees/sessions',
    registrations: 'employees/registrations',
    passwords: 'employees/passwords',
    confirmations: 'employees/confirmations'
  }
  devise_scope :employee do 
    get '/employee_detail/:id' => 'employees/registrations#employee_detail', as: :employee_detail
    get '/select_template' => 'employees/registrations#select_template', as: :select_template
    get '/preview_template/:id' => 'employees/registrations#preview_template', as: :preview_template
    get '/get_resume/:id' => 'employees/registrations#get_resume', as: :get_resume
  end
  namespace :employees do
    resources :profiles, only: [:show, :update]
  end
  
  namespace :admin do 
    resources :projects
    resources :employees
    resources :employee_projects
    resources :skills
    resources :templates
  end

  namespace :employee do
    get 'dashboard' => 'dashboard#index'
    get 'assignments' => 'dashboard#assignments'
    get 'dashboard/export_time_logs/:id', to: 'dashboard#export_time_logs', as: :export_time_logs
    get 'timesheets' => 'timesheets#index'
    get 'log_time' => 'timesheets#log_time'
    get 'project_time_sheet' => 'timesheets#project_time_sheet'
    get 'assign_task' => 'tasks#assign_task'
    post 'assign_task_to_employee' => 'tasks#assign_task_to_employee'
    resources :tasks do
      collection do 
        get :fetch_project_tasks
      end
    end
    resources :time_logs do 
      collection do
        get :fetch_logged_dates
      end
    end
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  validates :name, presence: true
end

app/controllers/admin/skills_controller.rb
class Admin::SkillsController < AdminController
  before_action :set_skill, only: %i[edit update destroy]
  def index
    @skills = Skill.order(created_at: :desc)
  end

  def edit; end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      render_turbo_stream(
        'prepend',
        'skill-list',
        'admin/skills/skill',
        { skill: @skill }
      )
    else
      render_turbo_stream(
        'replace',
        'remote_modal',
        'shared/turbo_modal',
        {
          form_partial: 'admin/skills/form',
          modal_title: 'Add New skill'
        }
      )
    end
  end

  def update
    if @skill.update(skill_params)
      render_turbo_stream(
        'replace',
        "skill-item-#{@skill.id}",
        'admin/skills/skill',
        { skill: @skill }
      )
    else
      render_turbo_stream(
        'replace',
        'remote_modal',
        'shared/turbo_modal',
        { 
          form_partial: 'admin/skills/form', 
          modal_title: 'Edit skill' 
        }
      )
    end
  end

  def destroy
    @skill.destroy
    render_turbo_stream(
      'remove',
      "skill-item-#{@skill.id}"
    )
  end

  private

  def set_skill
    @skill = Skill.find(params[:id])
  end

  def skill_params
    params.require(:skill).permit(:name)
  end
end

app/views/admin/skills/_form.html.erb
<%= form_with(model: [:admin, @skill]) do |form| %>
  <div class="modal-body">
    <div class="row">
      <% if @skill.errors.any? %>
        <div class="error-area" style="color:red;">
          <h3><%= pluralize(@skill.errors.count, 'error') %> prohibited your skill from being saved.</h3>
          <ul>
            <% @skill.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="col-lg-12">
        <div class="form-group">
          <label class="mb-2 mt-3">
            Name
            <span class="text-danger">*</span>
          </label>
          <%= form.text_field :name, class: "form-control" %>
        </div>
      </div>
    </div>

  </div>
  <div class="modal-footer">
    <%= form.submit 'Save Changes', class: 'btn btn-primary', data: { action: 'click->bs-modal#submitEnd' } %>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
  </div>
<% end %>

app/views/admin/skills/_skill.html.erb
<tr id="skill-item-<%= skill.id %>">
  <td><%= skill.name %></td>
  <td>
    <%= link_to 'Edit', edit_admin_skill_path(skill), class: 'btn btn-warning', data: { controller: "bs-modal-form" } %>
    <%= link_to 'Delete', admin_skill_path(skill), class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this skill? This action can not be undo.' } %>
  </td>
</tr>

app/views/admin/skills/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'shared/turbo_modal', modal_title: 'Edit Skill', form_partial: "admin/skills/form" %>
<% end %>

app/views/admin/skills/index.html.erb
<%= link_to "New Skill", new_admin_skill_path, class: "btn btn-primary mb-3", data: { controller: "bs-modal-form" } %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody id="skill-list">
    <% @skills.each do |skill| %>
      <%= render "admin/skills/skill", skill: skill %>
    <% end %>
  </tbody>
</table>

app/views/admin/skills/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'shared/turbo_modal', modal_title: 'Add Skill', form_partial: "admin/skills/form" %>
<% end %>