config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :employees, controllers: {
    sessions: 'employees/sessions',
    registrations: 'employees/registrations',
    passwords: 'employees/passwords',
    confirmations: 'employees/confirmations'
  }
  devise_scope :employee do 
    get '/employee_detail/:id' => 'employees/registrations#employee_detail', as: :employee_detail
    get '/select_template' => 'employees/registrations#select_template', as: :select_template
    get '/preview_template/:id' => 'employees/registrations#preview_template', as: :preview_template
    get '/get_resume/:id' => 'employees/registrations#get_resume', as: :get_resume
  end
  namespace :employees do
    resources :profiles, only: [:show, :update]
  end
  
  namespace :admin do 
    resources :projects
    resources :employees
    resources :employee_projects
    resources :skills
    resources :templates
  end

  namespace :employee do
    get 'dashboard' => 'dashboard#index'
    get 'assignments' => 'dashboard#assignments'
    get 'dashboard/export_time_logs/:id', to: 'dashboard#export_time_logs', as: :export_time_logs
    get 'timesheets' => 'timesheets#index'
    get 'log_time' => 'timesheets#log_time'
    get 'project_time_sheet' => 'timesheets#project_time_sheet'
    get 'assign_task' => 'tasks#assign_task'
    post 'assign_task_to_employee' => 'tasks#assign_task_to_employee'
    resources :tasks do
      collection do 
        get :fetch_project_tasks
      end
    end
    resources :time_logs do 
      collection do
        get :fetch_logged_dates
      end
    end
  end
end

app/views/shared/_admin_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><%#= current_employee.company.name %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Settings
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if employee_signed_in? %>
              <li><%= link_to 'Sign Out', destroy_employee_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to sign out?' }, class: 'dropdown-item' %></li>
            <% else %>
              <li><%= link_to 'Sign In', new_employee_session_path, class: 'dropdown-item' %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_admin_side_bar.html.erb
<div class="list-group">
  <%= link_to "Projects", admin_projects_path, class: "list-group-item list-group-item-action" %>
  <%= link_to "Employees", admin_employees_path, class: "list-group-item list-group-item-action" %>
  <%= link_to "Assignments", admin_employee_projects_path, class: "list-group-item list-group-item-action" %>
  <%= link_to "Skills", admin_skills_path, class: "list-group-item list-group-item-action" %>
  <%= link_to "Templates", admin_templates_path, class: "list-group-item list-group-item-action" %>
</div>

app/views/shared/_employee_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container-fluid">
    <a class="navbar-brand" href="#"><%= current_employee&.company&.name %></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle active active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Settings
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if employee_signed_in? %>
              <li><%= link_to 'Sign Out', destroy_employee_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to sign out?' }, class: 'dropdown-item' %></li>
            <% else %>
              <li><%= link_to 'Sign In', new_employee_session_path, class: 'dropdown-item' %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_employee_side_bar.html.erb
<div class="list-group">
  <%= link_to "Dashboard", employee_dashboard_path, class: "list-group-item list-group-item-action" %>
  <%= link_to "Assignments", employee_assignments_path, class: "list-group-item list-group-item-action" %>
  <%= link_to "Tasks", employee_tasks_path, class: "list-group-item list-group-item-action" %>
  <%= link_to "Timesheets", employee_timesheets_path, class: "list-group-item list-group-item-action" %>
  <%#= link_to "Settings", edit_employee_registration_path, class: "list-group-item list-group-item-action" %>
  <% if employee_signed_in? && current_employee.project_manager? %>
    <%= link_to employee_assign_task_path, class: 'bg-primary  mt-4 list-group-item text-white text-center fs-5', data: { controller: "bs-modal-form", remote: true } do %>
      <i class="bi bi-plus"></i> Assign Task
    <% end %>
  <% end %>
  <% if employee_signed_in? && employee_basic_details?(current_employee) %>
    <%= link_to "Create Resume", edit_employee_registration_path, class: "btn btn-secondary" %>
  <% end %>
</div>

app/views/shared/_export_modal.html.erb
<!-- Modal Structure -->
<div class="modal fade" id="exportModal" tabindex="-1" data-controller="export-options" aria-labelledby="exportModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exportModalLabel">Export Options</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form_with url: export_path, method: :get, data: { turbo: "true"}, html: { data: { export_options_target: "form" } } do |form| %>
          <% if params[:q].present? %>
						<% params[:q].each do |key, value| %>
				      <%= hidden_field_tag "q[#{key}]", value %>
				    <% end %>
				  <% end %>  
          <% if params[:action] == "assignments" %>
	          <div class="mb-3">
					    <%= form.label :date_range, 'Select Date Range', class: 'form-label' %>
					    <%= form.text_field :date_range, 
					        id: 'date_range', 
					        class: 'form-control', 
					        placeholder: 'YYYY-MM-DD to YYYY-MM-DD', 
					        data: { export_options_target: 'dateField', controller: 'flatpickr', range_select: true } %>
					  </div>
					<% end %>
				  <div class="mb-3">
				    <div class="d-flex align-items-center">
				      <div class="form-check me-3">
				        <%= check_box_tag 'export_option[]', 'download', false, class: 'form-check-input', data: { export_options_target: 'checkbox' } %>
				        <%= form.label :download, 'Download', class: 'form-check-label' %>
				      </div>
				      <div class="form-check">
				        <%= check_box_tag 'export_option[]', 'email', false, class: 'form-check-input', data: { export_options_target: 'checkbox' } %>
				        <%= form.label :email, 'Email Me', class: 'form-check-label' %>
				      </div>
				    </div>
				  </div>

				  <div class="modal-footer">
				    <%= form.submit 'Proceed', class: 'btn btn-primary' %>
				  </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<div class="container" id="flash">
  <% flash.each do |key, value| %>
  <div class="<%= flash_class(key.to_sym)%> alert-dismissible fade show" role="alert">
    <% unless value == true %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= value %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/shared/_turbo_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="modal fade" id="bsTurboModal" tabindex="-1" aria-labelledby="bsTurboModalLabel" aria-hidden="true" data-controller="bs-modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="bsTurboModalLabel"><%= modal_title %></h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <%= render form_partial %>
      </div>
    </div>
  </div>
<% end %>