config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :employees, controllers: {
    sessions: 'employees/sessions',
    registrations: 'employees/registrations',
    passwords: 'employees/passwords',
    confirmations: 'employees/confirmations'
  }
  devise_scope :employee do 
    get '/employee_detail/:id' => 'employees/registrations#employee_detail', as: :employee_detail
    get '/select_template' => 'employees/registrations#select_template', as: :select_template
    get '/preview_template/:id' => 'employees/registrations#preview_template', as: :preview_template
    get '/get_resume/:id' => 'employees/registrations#get_resume', as: :get_resume
  end
  namespace :employees do
    resources :profiles, only: [:show, :update]
  end
  
  namespace :admin do 
    resources :projects
    resources :employees
    resources :employee_projects
    resources :skills
    resources :templates
  end

  namespace :employee do
    get 'dashboard' => 'dashboard#index'
    get 'assignments' => 'dashboard#assignments'
    get 'dashboard/export_time_logs/:id', to: 'dashboard#export_time_logs', as: :export_time_logs
    get 'timesheets' => 'timesheets#index'
    get 'log_time' => 'timesheets#log_time'
    get 'project_time_sheet' => 'timesheets#project_time_sheet'
    get 'assign_task' => 'tasks#assign_task'
    post 'assign_task_to_employee' => 'tasks#assign_task_to_employee'
    resources :tasks do
      collection do 
        get :fetch_project_tasks
      end
    end
    resources :time_logs do 
      collection do
        get :fetch_logged_dates
      end
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  STATUS = %w(Active Inactive Completed Hold Finished)
  has_many :employee_projects
  has_many :employees, through: :employee_projects

  belongs_to :company
  has_many :tasks

  validates :title, :client_name, :client_company, :start_date, :status, presence: true
  validates :title, uniqueness: true
  
  def display_name
    "#{title} (#{company})"
  end

  def self.ransackable_attributes(auth_object = nil)
    ["client_company", "client_name", "company_id", "created_at", "end_date", "id", "start_date", "status", "title", "updated_at"]
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController
  before_action :set_project, only: %i[show edit update destroy]
  def index
    @projects = current_company.projects.order(created_at: :desc)
  end

  def show
    @employees = @project.employees
    @tasks = @project.tasks
  end

  def edit; end

  def new
    @project = current_company.projects.new
  end

  def create
    @project = current_company.projects.new(project_params)
    if @project.save
      render_turbo_stream(
        'prepend',
        'project-list',
        'admin/projects/project',
        { project: @project }
      )
    else
      render_turbo_stream(
        'replace',
        'remote_modal',
        'shared/turbo_modal',
        {
          form_partial: 'admin/projects/form',
          modal_title: 'Add New Project'
        }
      )
    end
  end

  def update
    if @project.update(project_params)
      render_turbo_stream(
        'replace',
        "project-item-#{@project.id}",
        'admin/projects/project',
        { project: @project }
      )
    else
      render_turbo_stream(
        'replace',
        'remote_modal',
        'shared/turbo_modal',
        { 
          form_partial: 'admin/projects/form', 
          modal_title: 'Edit project' 
        }
      )
    end
  end

  def destroy
    @project.destroy
    render_turbo_stream(
      'remove',
      "project-item-#{@project.id}"
    )
  end

  private

  def set_project
    @project = current_company.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :client_name, :client_company, :start_date, :end_date, :status)
  end
end

app/views/admin/projects/_form.html.erb
<%= form_with(model: [:admin, @project]) do |form| %>
  <div class="modal-body">
    <div class="row">
      <% if @project.errors.any? %>
        <div class="error-area" style="color:red;">
          <h3><%= pluralize(@project.errors.count, 'error') %> prohibited your project from being saved.</h3>
          <ul>
            <% @project.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="col-lg-12">
        <div class="form-group">
          <label class="mb-2 mt-3">
            Title
            <span class="text-danger">*</span>
          </label>
          <%= form.text_field :title, class: "form-control" %>
        </div>

        <div class="form-group">
          <label class="mb-2 mt-3">
            Client Company
            <span class="text-danger">*</span>
          </label>
          <%= form.text_field :client_company, class: "form-control" %>
        </div>

        <div class="form-group">
          <label class="mb-2 mt-3">
            Client
            <span class="text-danger">*</span>
          </label>
          <%= form.text_field :client_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <label class="mb-2 mt-3">
            Status
            <span class="text-danger">*</span>
          </label>
          <%= form.select :status, options_for_select(Project::STATUS, selected: form.object.status), {prompt: 'Select Project Status'}, { class: "form-select" } %>
        </div>

        <div class="form-group row">
          <div class="col-lg-6">
            <label class="mb-2 mt-3">
              Start Date
              <span class="text-danger">*</span>
            </label>
            <%= form.date_field :start_date, class: "form-control" %>
          </div>
          <div class="col-lg-6">
            <label class="mb-2 mt-3">
              End Date
            </label>
            <%= form.date_field :end_date, class: "form-control" %>
          </div>
        </div>
      </div>
    </div>

  </div>
  <div class="modal-footer">
    <%= form.submit 'Save Changes', class: 'btn btn-primary', data: { action: 'click->bs-modal#submitEnd' } %>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
  </div>
<% end %>

app/views/admin/projects/_project.html.erb
<tr id="project-item-<%= project.id %>">
  <td><%= project.title %></td>
  <td><%= project.client_company %></td>
  <td>
    <%= link_to 'Show', admin_project_path(project), class: 'btn btn-info', data: { controller: "bs-modal-form" } %>
    <%= link_to 'Edit', edit_admin_project_path(project), class: 'btn btn-warning', data: { controller: "bs-modal-form" } %>
    <%= link_to 'Delete', admin_project_path(project), class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this project? This action can not be undo.' } %>
  </td>
</tr>

app/views/admin/projects/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'shared/turbo_modal', modal_title: 'Edit Project', form_partial: "admin/projects/form" %>
<% end %>

app/views/admin/projects/index.html.erb
<%= link_to "New Project", new_admin_project_path, class: "btn btn-primary mb-3", data: { controller: "bs-modal-form" } %>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Title</th>
      <th>Company</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody id="project-list">
    <% @projects.each do |project| %>
      <%= render "admin/projects/project", project: project %>
    <% end %>
  </tbody>
</table>

app/views/admin/projects/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'shared/turbo_modal', modal_title: 'Add New Project', form_partial: "admin/projects/form" %>
<% end %>

app/views/admin/projects/show.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= turbo_frame_tag :remote_modal, target: :_top do %>
    <div class="modal fade" id="bsTurboModal" tabindex="-1" aria-labelledby="bsTurboModalLabel" aria-hidden="true" data-controller="bs-modal">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="bsTurboModalLabel">Project Details</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p class="lead"><strong>Title: </strong><%= @project.title %></p>
            <p class="lead"><strong>Client: </strong><%= @project.client_name %></p>
            <p class="lead"><strong>Client Company: </strong><%= @project.client_company %></p>
            <p class="lead"><strong>Status: </strong><%= @project.status %></p>
            <p class="lead"><strong>Start Date: </strong><%= @project.start_date %></p>
            <% if @project.end_date.present? %>
              <p class="lead"><strong>End Date: </strong><%= @project.end_date %></p>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>