config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :employees, controllers: {
    sessions: 'employees/sessions',
    registrations: 'employees/registrations',
    passwords: 'employees/passwords',
    confirmations: 'employees/confirmations'
  }
  devise_scope :employee do 
    get '/employee_detail/:id' => 'employees/registrations#employee_detail', as: :employee_detail
    get '/select_template' => 'employees/registrations#select_template', as: :select_template
    get '/preview_template/:id' => 'employees/registrations#preview_template', as: :preview_template
    get '/get_resume/:id' => 'employees/registrations#get_resume', as: :get_resume
  end
  namespace :employees do
    resources :profiles, only: [:show, :update]
  end
  
  namespace :admin do 
    resources :projects
    resources :employees
    resources :employee_projects
    resources :skills
    resources :templates
  end

  namespace :employee do
    get 'dashboard' => 'dashboard#index'
    get 'assignments' => 'dashboard#assignments'
    get 'dashboard/export_time_logs/:id', to: 'dashboard#export_time_logs', as: :export_time_logs
    get 'timesheets' => 'timesheets#index'
    get 'log_time' => 'timesheets#log_time'
    get 'project_time_sheet' => 'timesheets#project_time_sheet'
    get 'assign_task' => 'tasks#assign_task'
    post 'assign_task_to_employee' => 'tasks#assign_task_to_employee'
    resources :tasks do
      collection do 
        get :fetch_project_tasks
      end
    end
    resources :time_logs do 
      collection do
        get :fetch_logged_dates
      end
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :registerable,
         :recoverable, 
         :rememberable, 
         :validatable, 
         :trackable
  
  has_one_attached :profile_image
  has_many :employee_projects
  has_many :projects, through: :employee_projects
  belongs_to :company, optional: true
  has_many :tasks
  has_many :time_logs

  has_many :education_records, dependent: :destroy
  accepts_nested_attributes_for :education_records, allow_destroy: true

  has_many :work_experiences, dependent: :destroy
  accepts_nested_attributes_for :work_experiences, allow_destroy: true

  has_many :employee_hobbies
  has_many :hobbies, through: :employee_hobbies
  has_many :employee_skills
  has_many :skills, through: :employee_skills
  has_many :resumes, dependent: :destroy  # Add this line
  has_one :social_network, dependent: :destroy
  accepts_nested_attributes_for :social_network, allow_destroy: true


  validates :first_name, :last_name, :job_title, presence: true
  validates :about, :profile_image, presence: true, if: :editing_record?
  validates :contact_number, presence: true, uniqueness: true, format: { with: /\A\d{10}\z/, message: "must be 10 digits long" }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validate :first_and_last_name_format

  before_save :set_default_role
  after_create :send_set_password_email

  # Skip current password validation if only certain attributes are being updated

  def editing_record?
    persisted? # Returns true if the record has been saved (i.e., editing)
  end

  def set_default_role
    self.role = 'developer' unless role.present?
  end

  def developer?
    role == 'developer'
  end

  def admin_employee?
    role == 'admin'
  end

  def project_manager?
    role == 'project_manager'
  end

  def full_name
    "#{first_name} #{last_name}".strip
  end

  def password_required?
    false
  end

  def send_set_password_email
    self.send_reset_password_instructions
  end

  def first_and_last_name_format
    if first_name.present? && !first_name.match?(/\A[a-zA-Z]+\z/)
      errors.add(:first_name, "must only contain letters (A-Z, a-z)")
    end

    if last_name.present? && !last_name.match?(/\A[a-zA-Z]+\z/)
      errors.add(:last_name, "must only contain letters (A-Z, a-z)")
    end
  end
end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < AdminController
  before_action :set_employee, only: %i[show edit update destroy]
  def index
    @employees = current_company.employees.order(created_at: :desc)
  end

  def show
    @projects = @employee.projects
    @tasks = @employee.tasks
    @timesheet_logs = @employee.time_logs
  end

  def edit; end

  def new
    @employee = current_company.employees.new
  end

  def create
    @employee = current_company.employees.new(employee_params)
    if @employee.save
      render_turbo_stream(
        'prepend',
        'employee-list',
        'admin/employees/employee',
        { employee: @employee }
      )
    else
      render_turbo_stream(
        'replace',
        'remote_modal',
        'shared/turbo_modal',
        {
          form_partial: 'admin/employees/form',
          modal_title: 'Add New employee'
        }
      )
    end
  end

  def update
    if @employee.update(employee_params)
      render_turbo_stream(
        'replace',
        "employee-item-#{@employee.id}",
        'admin/employees/employee',
        { employee: @employee }
      )
    else
      render_turbo_stream(
        'replace',
        'remote_modal',
        'shared/turbo_modal',
        { 
          form_partial: 'admin/employees/form', 
          modal_title: 'Edit employee' 
        }
      )
    end
  end

  def destroy
    @employee.destroy
    render_turbo_stream(
      'remove',
      "employee-item-#{@employee.id}"
    )
  end

  private

  def set_employee
    @employee = current_company.employees.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:job_title, :first_name, :last_name, :email, :contact_number)
  end
end

app/controllers/employee/dashboard_controller.rb
class Employee::DashboardController < EmployeeController
  include CsvExportDefinitions
  include CsvExportable
  def index
    filter = params[:filter] || 'past_7_days'
    @time_logs = current_employee.time_logs.filter_by_days(filter)
    @total_hours = @time_logs.sum(:time_in_hours).round(1) # Calculate total hours worked

    # Group by week and calculate total hours
    @weekly_data = group_by_week(@time_logs)

    respond_to do |format|
      format.html
      format.turbo_stream
      format.json {
        Rails.logger.debug("Weekly Data: #{@weekly_data.inspect}")
        render json: { totalHours: @total_hours, labels: @weekly_data.keys.map(&:to_s), data: @weekly_data.values } 
      }
    end
  end

  def assignments
    @employee_projects = current_employee.employee_projects.includes(:project)
    @projects = current_employee.projects.where(id: @employee_projects.pluck(:project_id)).pluck(:title)
  end

  def export_time_logs
    employee_project = current_employee.employee_projects.find(params[:id])
    @time_logs = employee_project.time_logs

    filter_tasks_by_date if params[:date_range].present?
    respond_to do |format|
      format.html
      format.csv { handle_csv_export(@time_logs, TIME_LOG_HEADERS, TIME_LOG_MAPPINGS, employee_assignments_path, 'time_logs' ) }
    end
  end

  private
  # Filters time_logs based on the provided date range
  def filter_tasks_by_date
    start_date, end_date = params[:date_range].split(" to ").map(&:to_date)
    end_date = end_date.end_of_day
    @time_logs = @time_logs.where(log_date: start_date..end_date)
  end

  def group_by_week(time_logs)
    grouped_data = time_logs.group_by { |log| log.log_date.beginning_of_week }.transform_values do |logs|
      logs.sum(&:time_in_hours)
    end
    Rails.logger.debug("Grouped Data: #{grouped_data.inspect}")
    grouped_data
  end
end

app/controllers/employee/tasks_controller.rb
class Employee::TasksController < EmployeeController
  include Filterable
  include Pagy::Backend
  include CsvExportDefinitions
  include CsvExportable

  before_action :set_task, only: %i[show edit update destroy]
  before_action :load_projects, only: %i[edit new]

  def index
    @employee_projects = current_employee.employee_projects.includes(:project)
    @projects = current_employee.projects.where(id: @employee_projects.pluck(:project_id))
    @q = current_employee.tasks.includes(:project).ransack(params[:q])
    @tasks = filter_by_date_range(@q.result(distinct: true))
    respond_to do |format|
      format.html
      format.csv { handle_csv_export(@tasks, TASK_HEADERS, TASK_MAPPINGS, employee_tasks_path, 'tasks' ) }
    end
    # Paginate the results
    @pagy, @tasks = pagy(@tasks, items: 5)
  end
  
  def new
    @task = current_employee.tasks.new
  end

  def assign_task
    if current_employee.project_manager?
      @tasks = current_employee.tasks.includes(:project)
      @employee_projects = current_employee.employee_projects.includes(:project)
      @projects = current_employee.projects.where(id: @employee_projects.pluck(:project_id)).pluck(:title)
    end
  end

  def assign_task_to_employee
    @task = Task.find(params[:task_id])
    if @task.update(employee_id: params[:employee_id], project_id: params[:project_id])
      redirect_to employee_dashboard_path, notice: 'Task was successfully assigned.'
    else
      redirect_to employee_dashboard_path, alert: 'Failed to assign task.'
    end
  end

  def show; end

  def edit; end

  def create
    @task = current_employee.tasks.new(task_params)
    if @task.save
      render_turbo_stream(
        'prepend',
        'task-list',
        'employee/tasks/task',
        { task: @task }
      )
    else
      render_turbo_stream(
        'replace',
        'remote_modal',
        'shared/turbo_modal',
        {
          form_partial: 'employee/tasks/form',
          modal_title: 'Add New Task'
        }
      )
    end
  end

  def update
    if @task.update(task_params)
      render_turbo_stream(
        'replace',
        "task-item-#{@task.id}",
        'employee/tasks/task',
        { task: @task }
      )
    else
      render_turbo_stream(
        'replace',
        'remote_modal',
        'shared/turbo_modal',
        { 
          form_partial: 'employee/tasks/form', 
          modal_title: 'Edit Task' 
        }
      )
    end
  end

  def destroy
    @task.destroy
    render_turbo_stream(
      'remove',
      "task-item-#{@task.id}"
    )
  end

  def fetch_project_tasks
    employee_project = current_employee.employee_projects.find(params[:project_id])
    project_tasks = current_employee.tasks.where(project_id: employee_project.project_id)
    completed_task_ids = TimeLog.where(status: 'Completed').pluck(:task_id).uniq
    @tasks = project_tasks.where.not(id: completed_task_ids)
  end

  private

  def set_task
    @task = current_employee.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :number, :employee_id, :project_id)
  end

  def load_projects
    @projects = current_employee.projects
  end
end

app/controllers/employee/time_logs_controller.rb
class Employee::TimeLogsController < EmployeeController
  before_action :set_time_log, only: %i[update show]
  def new
    @time_log = current_employee.time_logs.new
  end

  def show;end

  def edit
    @time_log = current_employee.time_logs.find(params[:id])
    @tasks = current_employee.tasks.where(project_id: @time_log.employee_project.project_id)
  end

  def create
    @time_log = current_employee.time_logs.new(time_params)
    if @time_log.save
      render_turbo_stream(
        'prepend',
        'time-logged-list',
        'employee/time_logs/log',
        { time_log: @time_log }
      )
    else
      render_turbo_stream(
        'replace',
        'remote_modal',
        'shared/turbo_modal',
        {
          form_partial: 'employee/time_logs/form',
          modal_title: 'Add Time'
        }
      )
    end
  end

  def update
    if @time_log.update(time_params)
      render_turbo_stream(
        'replace',
        "time_log-item-#{@time_log.id}",
        'employee/time_logs/log',
        { time_log: @time_log }
      )
    else
      render_turbo_stream(
        'replace',
        'remote_modal',
        'shared/turbo_modal',
        { 
          form_partial: 'employee/time_logs/form', 
          modal_title: 'Edit Time Log' 
        }
      )
    end
  end

  def fetch_logged_dates
    @log_dates = current_employee.time_logs.pluck(:log_date).sort.map {|date| date.strftime("%d-%m-%Y")}
    render json: @log_dates
  end

  private

  def set_time_log
    @time_log = current_employee.time_logs.find(params[:id])
  end

  def time_params
    params.require(:time_log).permit(:description, :log_date, :status, :task_type, :time_in_hours, :task_id, :employee_project_id)
  end
end

app/controllers/employee/timesheets_controller.rb
class Employee::TimesheetsController < EmployeeController
  include Filterable
  include Pagy::Backend
  include CsvExportDefinitions
  include CsvExportable

  def index
    @employee_projects = current_employee.employee_projects.includes(:project)
    @projects = current_employee.projects.where(id: @employee_projects.pluck(:project_id))
    @q = current_employee.time_logs.includes(employee_project: :project).order(log_date: :desc).ransack(params[:q])
    @time_logs = filter_by_date_range(@q.result(distinct: true))

    respond_to do |format|
      format.html
      format.csv { handle_csv_export(@time_logs, TIME_LOG_HEADERS, TIME_LOG_MAPPINGS, employee_timesheets_path, 'time_logs') }
    end
    # Paginate the results
    @pagy, @time_logs = pagy(@time_logs, items: 5)
  end

  def project_time_sheet
    @project = EmployeeProject.find(params[:employee_project_id]).project
    @all_time_logs = current_employee.time_logs
                                     .includes(:task)
                                     .where(employee_project_id: params[:employee_project_id])
                                     .select(:task_id, :time_in_hours, :log_date, :status)

    @card_items = {
      'Total Tasks' => @all_time_logs.map(&:task_id).uniq.count,
      'Total Time Spent' => "#{@all_time_logs.sum(&:time_in_hours)} hours",
      'Total Work Days' => @all_time_logs.map(&:log_date).uniq.count
    }
  end

  def log_time
    @time_log = current_employee.time_logs.new
  end

  def edit_logged_time
    @time_log = current_employee.time_logs.find(params[:id])
  end
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
end

app/controllers/employees/confirmations_controller.rb
# frozen_string_literal: true

class Employees::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employees/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Employees::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employees/passwords_controller.rb
# frozen_string_literal: true

class Employees::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employees/sessions_controller.rb
# frozen_string_literal: true

class Employees::SessionsController < Devise::SessionsController
  layout 'application'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/employees/unlocks_controller.rb
# frozen_string_literal: true

class Employees::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/employee/tasks/_assign_task_form.html.erb
<% if @projects.present? && @tasks.present? %>
	<div class="modal-body">
		<%= form_with(model: @task, url: employee_assign_task_to_employee_path, method: :post) do |form| %>
			<div class="form-group mt-3">
				<%= form.label :project_id, "Select Project" %>
				<%= form.collection_select :project_id, @projects, :id, :title, { prompt: 'Select Project' }, { class: 'form-control' } %>
			</div>

			<div class="form-group mt-3">
				<%= form.label :task_id, "Select Task" %>
				<%= form.collection_select :task_id, @tasks, :id, :title, { prompt: 'Select Task' }, { class: 'form-control' } %>
			</div>

			<div class="form-group mt-3">
				<%= form.label :employee_id, "Select Employee" %>
				<%= form.collection_select :employee_id, Employee.all, :id, :full_name, { prompt: 'Select Employee' }, { class: 'form-control' } %>
			</div>
			<%= form.submit "Assign Task", class: 'btn btn-primary mt-3' %>
		<% end %>
	</div>
<% else %>
  <div class="card">
  	<div class="card-body">
      <h5>It looks like you don't have any projects or tasks yet. Please create a project and add tasks to it before assigning them to an employee.</h5>
  	</div>
  </div>
<% end %>

app/views/employee/tasks/_form.html.erb
<%= form_with(model: [:employee, @task]) do |form| %>
  <div class="modal-body">
    <div class="row">
      <% if @task.errors.any? %>
        <div class="error-area" style="color:red;">
          <h3><%= pluralize(@task.errors.count, 'error') %> prohibited your employee from being saved.</h3>
          <ul>
            <% @task.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="col-lg-12">
        <div class="form-group">
          <label class="mb-2 mt-3">
            Project
            <span class="text-danger">*</span>
          </label>
          <%= form.select :project_id, options_for_select(@projects.map {|project| [project.title, project.id]}, selected: form.object.project_id), { prompt: 'Select a project' }, { class: "form-select" } %>
        </div>

        <div class="form-group">
          <label class="mb-2 mt-3">
            Number
            <span class="text-danger">*</span>
          </label>
          <%= form.text_field :number, class: "form-control" %>
        </div>

        <div class="form-group">
          <label class="mb-2 mt-3">
            Title
            <span class="text-danger">*</span>
          </label>
          <%= form.text_field :title, class: "form-control" %>
        </div>
      </div>
    </div>

  </div>
  <div class="modal-footer">
    <%= form.submit 'Save Changes', class: 'btn btn-primary', data: { action: 'click->bs-modal#submitEnd' } %>
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
  </div>
<% end %>

app/views/employee/tasks/_task.html.erb
<tr id="task-item-<%= task.id %>">
  <td><%= task.project.title %></td>
  <td><%= task.title %></td>
  <td><%= task.number %></td>
  <td>
    <%= link_to 'Show', employee_task_path(task), class: 'btn btn-info', data: { controller: "bs-modal-form" } %>
    <%= link_to 'Edit', edit_employee_task_path(task), class: 'btn btn-warning', data: { controller: "bs-modal-form" } %>
    <%= link_to 'Delete', employee_task_path(task), class: 'btn btn-danger', data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this task? This action can not be undo.' } %>
  </td>
</tr>

app/views/employee/tasks/_task_filters.html.erb
<%= form_with(model: q, url: employee_tasks_path, method: "get", data: { turbo_form: true }) do |f| %>
  <div class="d-flex">
    <div class="form-group me-3">
      <%= f.label :project_id_eq, "Filter by Project:" %>
      <%= f.select :project_id_eq, options_for_select(@projects.map { |project| [project.title, project.id] }, f.object.project_id_eq), { prompt: "Select Project" }, { class: "form-control", onchange: "this.form.submit();"} %>
    </div>
    <div class="form-group">
      <label>Filter By dates</label>
      <%= text_field_tag "q[date_range]", nil, 
             class: 'form-control', 
             placeholder: 'Select Date', 
             data: { controller: 'flatpickr', range_select: 'true' }, value: @date_range %>
    </div>
    <div class="form-group mt-4 mx-3">
      <%= f.submit 'filter', class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/employee/tasks/assign_task.turbo_stream.erb
<%= turbo_stream.replace "flash" do %>
  <%= render partial: "shared/flash" %>
<% end %>

<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'shared/turbo_modal', modal_title: 'Assign Task', form_partial: "employee/tasks/assign_task_form" %>
<% end %>

app/views/employee/tasks/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'shared/turbo_modal', modal_title: 'Edit Task', form_partial: "employee/tasks/form" %>
<% end %>

app/views/employee/tasks/fetch_project_tasks.turbo_stream.erb
<% if @tasks.present? %>
  <%= turbo_stream.replace 'project-tasks-list' do %>
    <div class="col-lg-12" id="project-tasks-list">
      <label class="mb-2 mt-3">
        Select Task
        <span class="text-danger">*</span>
      </label>
      <select class="form-select" name="time_log[task_id]" id="time_log_task_id">
        <% @tasks.each do |task| %>
          <option value="<%= task.id %>"><%= task.display_title %></option>
        <% end %>
      </select>
    </div>
  <% end %>
<% else %>
  <%= turbo_stream.replace 'project-tasks-list' do %>
    <div class="col-lg-12" id="project-tasks-list">
      <p class="mt-3 no-task">No tasks present for this projects.</p>
    </div>
  <% end %>
<% end %>

app/views/employee/tasks/index.html.erb
<% content_for :title, 'AiProjectMgmt | Employee Tasks' %>
<% if @tasks.present? %>
  <div class="row mt-3">
    <div class="d-flex align-items-center">
      <div class="mb-3">
        <%= render 'task_filters', q: @q, projects: @projects %>
      </div>  
    </div>
    <div class="text-end mb-3">
      <%= link_to "New Task", new_employee_task_path, class: "btn btn-primary", data: { controller: "bs-modal-form" } %>

      <%= link_to 'Export', '#exportModal', class: 'btn btn-primary', data: { bs_toggle: 'modal' } %>
    </div>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Project</th>
        <th>Title</th>
        <th>Number</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody id="task-list">
      <% @tasks.each do |task| %>
        <%= render "employee/tasks/task", task: task %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="card mt-4">
    <div class="card-body">
      <h4>No tasks found for the selected project.</h4>
    </div>
  </div>
<% end %>
<div class="pag-bar mt-5 pt-5">
  <%== pagy_bootstrap_nav(@pagy) if @pagy.pages > 1  %>
</div>
<%= render 'shared/export_modal', export_path: employee_tasks_path(format: :csv), modal_title: 'Export Options' %>

app/views/employee/tasks/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render 'shared/turbo_modal', modal_title: 'Add New Task', form_partial: "employee/tasks/form" %>
<% end %>

app/views/employee/tasks/show.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= turbo_frame_tag :remote_modal, target: :_top do %>
    <div class="modal fade" id="bsTurboModal" tabindex="-1" aria-labelledby="bsTurboModalLabel" aria-hidden="true" data-controller="bs-modal">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="bsTurboModalLabel">Task Details</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p class="lead"><strong>Title: </strong><%= @task.project.title %></p>
            <p class="lead"><strong>Employee: </strong><%= @task.employee.full_name %></p>
            <p class="lead"><strong>Task: </strong><%= @task.display_title %></p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>